# Numpy

NumPy adalah pustaka sumber terbuka yang tersedia dengan Python yang membantu dalam pemrograman matematika, ilmiah, teknik, dan sains data. 
NumPy adalah perpustakaan luar biasa untuk melakukan operasi matematika dan statistik. Ia bekerja dengan sangat baik untuk larik multi-dimensi dan perkalian matriks


In [1]:
import numpy as np

In [2]:
arr1_list=[1,5,3,8,10]
a=np.array(arr1_list)
a

array([ 1,  5,  3,  8, 10])

In [3]:
#Jumlah kolom
print(a.shape)

(5,)


In [4]:
#Array bilangan bulat
print(a.dtype) 

int32


In [5]:
#Array dengan Desimal
b=np.array([1.3, 5.8, 3.2, 8.5, 10,2 ])
print(b.dtype)

float64


In [10]:
#Perkalian
c = a * 10
print(c)

[ 10  50  30  80 100]


In [7]:
#Array 2 dimensi
arr2_list=[(2, 6, 8, 4), (9, 2, 6, 7)]
d=np.array(arr2_list)

# Menghasilkan array 2x4
print(d.shape)

(2, 4)


In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(6,12)

array([ 6,  7,  8,  9, 10, 11])

In [64]:
np.arange(6,12,2)

array([ 6,  8, 10])

In [68]:
#array 3 dimensi
arr3_list=([[3, 2,3],
[4, 5, 6]],
[[7, 8,9],
[10, 11, 12]])
e=np.array(arr3_list)

# Menghasilkan array 2x2x3
print(e.shape)

(2, 2, 3)


## np.zeros and np.ones

In [3]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [4]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.random.randint(0,10)

4

In [8]:
np.random.randint(0,10,(4,4))

array([[3, 2, 7, 1],
       [4, 5, 6, 0],
       [1, 3, 5, 1],
       [3, 3, 0, 3]])

In [7]:
np.random.randint(0,10)

6

In [6]:
np.random.randint(0,10,(5,5))

array([[0, 7, 9, 1, 2],
       [0, 7, 9, 6, 3],
       [6, 8, 0, 1, 8],
       [3, 1, 2, 1, 9],
       [6, 4, 0, 4, 6]])

## Linspace
Linspace memberikan sampel dengan jarak yang sama.
Sintax: numpy.linspace(start, stop, num, endpoint)
Here,
Start: Nilai Awal urutan
Stop: Nilai Akhir urutan
Num: Jumlah sampel yang akan dihasilkan. Default-nya adalah 50
Endpoint: Jika True (default), stop adalah nilai terakhir. Jika False, nilai stop tidak disertakan.

In [5]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [6]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Index

In [3]:
matrix = np.arange(0,25).reshape(5,5)

In [4]:
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
print('Baris Pertama:', matrix[0])

Baris Pertama: [0 1 2 3 4]


In [6]:
print('Baris Kedua:', matrix[1])

Baris Kedua: [5 6 7 8 9]


In [11]:
# Pada numpy kolom pertama dan baris pertama dimulai dari 0
baris = 0
kolom = 1
matrix[baris,kolom]

1

In [12]:
baris = 2
kolom = 3
matrix[baris,kolom]

13

In [13]:
matrix[:,1]

array([ 1,  6, 11, 16, 21])

In [14]:
matrix[:,2]

array([ 2,  7, 12, 17, 22])

In [15]:
matrix[0]

array([0, 1, 2, 3, 4])

In [16]:
matrix[3]

array([15, 16, 17, 18, 19])

In [17]:
matrix[0:2,0:2]

array([[0, 1],
       [5, 6]])

## Masking
Masking adalah array yang menentukan setiap elemen dari array terkait apakah nilainya valid atau tidak 

In [18]:
matrix > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
mat=matrix[matrix > 10]
print(mat)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [20]:
mat.reshape(2,7)

array([[11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24]])

# LATIHAN

In [104]:
# Buat Array 7 x 7

In [105]:
# Kalikan array tersebut dengan 3

In [106]:
# buat array 7 x 7 dengan nilai 0 ==> gunakan perintah zero

In [107]:
# buat 5 x 6 dengan nilai 1 ==> gunakan perintah ones

In [108]:
# buat array 4 x 3 dengan nilai random

In [109]:
# Buat array 8 x 8

In [110]:
# Tampilkan baris pertama, baris pertama kolom ke 2

In [111]:
# cari nilai array yang lebih dari 8

In [ ]:
# dari hasil diatas Buat array 5 x 11 ==> Gunakan perintah reshape